name: Trigger Github Action to Update Submodules and Build in Other repo

on:
  push:
    branches:
      - main  # or the branch of your choice

jobs:
  trigger-remote-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: hiAndrewQuinn/til-site
          event-type: trigger-existing-action
